source      'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
#use_frameworks!

inhibit_all_warnings!

target :GKiOSApp  do
    #-------- 开源第三方库 -----
    pod 'ATKit_ObjectC',:git => 'https://github.com/tianya2416/ATKit_ObjectC.git'
    pod 'FMDB'
    pod 'Masonry'
    pod 'AFNetworking'
    pod 'YYKit'
    pod 'SDWebImage'
    pod 'EAIntroView'
    pod 'IDMPhotoBrowser'
    pod 'MMPopupView', :git => 'https://github.com/CoderLT/MMPopupView.git'
    pod 'MJRefresh', :git => 'https://github.com/CoderLT/MJRefresh.git'
    pod 'MBProgressHUD',:git => 'https://github.com/tianya2416/MBProgress.git'
    pod 'VTMagic',:git => 'https://github.com/tianya2416/VTMagicMacro.git'
    pod 'YNPageViewController',:git => 'https://gitee.com/tianya24/YNPageViewController.git'
    pod 'DZNEmptyDataSet'
    pod 'KVOController'
    pod 'FDFullscreenPopGesture', '1.1'
    pod 'PLPlayerKit'    , :podspec => 'https://raw.githubusercontent.com/pili-engineering/PLPlayerKit/master/PLPlayerKit-Universal.podspec'
    pod 'HHTransition'
    pod 'SDCycleScrollView'
    pod 'KLRecycleScrollView'
    pod 'ZFPlayer', '~> 3.0'
    pod 'ZFPlayer/ControlView', '~> 3.0'
    pod 'ZFPlayer/AVPlayer', '~> 3.0'
    pod 'VIMediaCache'
    pod 'HWPanModal'
    pod 'HWPopController'
    pod 'JXCategoryView'
end

