platform :ios, '8.0'
#use_frameworks!

inhibit_all_warnings!

target :GKiOSApp  do
    #-------- 开源第三方库 -----
    pod 'AppBaseCategory'
    pod 'FMDB'
    pod 'Masonry'
    pod 'AFNetworking'
    pod 'YYKit'
    pod 'SDWebImage'
    pod 'EAIntroView'
    pod 'Qiniu', '~> 7.1.8'
    pod 'IDMPhotoBrowser'
    pod 'MMPopupView', :git => 'https://github.com/CoderLT/MMPopupView.git'
    pod 'MJRefresh', :git => 'https://github.com/CoderLT/MJRefresh.git'
    pod 'MBProgressHUD',:git => 'https://github.com/tianya2416/MBProgress.git'
    pod 'VTMagic',:git => 'https://github.com/tianya2416/VTMagicMacro.git'
    pod 'DZNEmptyDataSet'
    pod 'KVOController'
    pod 'QBImagePickerController'
    pod 'MGJRouter'
    pod 'FDFullscreenPopGesture', '1.1'
    pod 'PLPlayerKit', :podspec => 'https://raw.githubusercontent.com/pili-engineering/PLPlayerKit/master/PLPlayerKit-Universal.podspec'
    pod 'TXLiteAVSDK_Player'
    pod 'HHTransition'
    pod 'SDCycleScrollView'
    pod 'KLRecycleScrollView'
    pod 'ZFPlayer', '~> 3.0'
    pod 'ZFPlayer/ControlView', '~> 3.0'
    pod 'ZFPlayer/AVPlayer', '~> 3.0'
#    pod 'YBImageBrowser'
end

